### ISSUE TITLE
Filter and Columns Localization by switching language is not working

### ISSUE THREAD

**Issue by kalbunna** [bogdan/datagrid#169]
I have use Datagrid to filter and show data . Now I try to apply multiple languages but the header always show the first configuration language. For instance, let say that I have two locale files
 en.yml

```
datagrid:
    form:
      search: Search
      reset: Reset
    columns:
      clients:
        name: Name

```
and km.yml

 ```
datagrid:
    form:
      search: ស្វែងរក
      reset: សំអាត
    columns:
      clients:
        name: អាត
```

In the filter i just call : 
`filter(:name, :string, header: I18n.t('datagrid.columns.clients.name')}) { |value, scope| scope.first_name_like(value) }`

I am waiting to hearing from you.
Thank you in advance 

Kind regards
